[data]
min_molecules_per_gene = 50
min_molecules_per_cell = 30

[segmentation]
scale = 6.15 # Negative values mean it must be estimated from `min_molecules_per_cell`

[plotting]
gene_composition_neigborhood = 70
